"""create_initial_schema

Revision ID: 8ffd8b42e2f7
Revises: 
Create Date: 2026-09-02 13:29:51.958825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '8ffd8b42e2f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_code', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('objective', sa.String(length=100), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_run_code'), 'optimization_runs', ['run_code'], unique=True)
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('scenario_parameters', sa.JSON(), nullable=True),
    sa.Column('baseline_metrics', sa.JSON(), nullable=True),
    sa.Column('simulated_metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_simulation_code'), 'simulation_runs', ['simulation_code'], unique=True)
    op.create_table('stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('division', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_station_code'), 'stations', ['station_code'], unique=True)
    op.create_table('trains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_code', sa.String(length=30), nullable=False),
    sa.Column('train_number', sa.String(length=30), nullable=False),
    sa.Column('train_name', sa.String(length=100), nullable=False),
    sa.Column('train_type', sa.Enum('PASSENGER', 'EXPRESS', 'FREIGHT', 'OTHER', name='traintype'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_train_code'), 'trains', ['train_code'], unique=True)
    op.create_index(op.f('ix_trains_train_number'), 'trains', ['train_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CONTROLLER', 'MAINTENANCE', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('railway_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_station_id', sa.Integer(), nullable=False),
    sa.Column('end_station_id', sa.Integer(), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('traffic_level', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['end_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['start_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_sections_end_station_id'), 'railway_sections', ['end_station_id'], unique=False)
    op.create_index(op.f('ix_railway_sections_section_code'), 'railway_sections', ['section_code'], unique=True)
    op.create_index(op.f('ix_railway_sections_start_station_id'), 'railway_sections', ['start_station_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_code', sa.String(length=30), nullable=False),
    sa.Column('asset_type', sa.Enum('TRACK', 'SIGNAL', 'POINTS', 'ELECTRICAL', 'BRIDGE', 'OTHER', name='assettype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='criticalitylevel'), nullable=False),
    sa.Column('condition_score', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('last_maintenance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['railway_sections.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_assets_section_id'), 'assets', ['section_id'], unique=False)
    op.create_index(op.f('ix_assets_station_id'), 'assets', ['station_id'], unique=False)
    op.create_table('block_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('window_code', sa.String(length=30), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='chk_block_window_times'),
    sa.ForeignKeyConstraint(['section_id'], ['railway_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_windows_section_id'), 'block_windows', ['section_id'], unique=False)
    op.create_index(op.f('ix_block_windows_window_code'), 'block_windows', ['window_code'], unique=True)
    op.create_table('train_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['railway_sections.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_train_mov_window', 'train_movements', ['section_id', 'scheduled_arrival', 'scheduled_departure'], unique=False)
    op.create_index(op.f('ix_train_movements_section_id'), 'train_movements', ['section_id'], unique=False)
    op.create_index(op.f('ix_train_movements_train_id'), 'train_movements', ['train_id'], unique=False)
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_code', sa.String(length=30), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('maintenance_type', sa.String(length=100), nullable=False),
    sa.Column('department', sa.Enum('ENGINEERING', 'OHE', 'SIGNALLING', name='department'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='maintenancestatus'), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('earliest_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overdue_days', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('traffic_impact_score', sa.Float(), nullable=False),
    sa.Column('crew_required', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority_score >= 0 AND priority_score <= 100', name='chk_priority_score_range'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='chk_risk_score_range'),
    sa.CheckConstraint('traffic_impact_score >= 0 AND traffic_impact_score <= 100', name='chk_traffic_score_range'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['railway_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_maint_task_search', 'maintenance_tasks', ['section_id', 'status', 'due_date', 'priority_score'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_asset_id'), 'maintenance_tasks', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_due_date'), 'maintenance_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_priority_score'), 'maintenance_tasks', ['priority_score'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_section_id'), 'maintenance_tasks', ['section_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_status'), 'maintenance_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_task_code'), 'maintenance_tasks', ['task_code'], unique=True)
    op.create_table('optimized_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_code', sa.String(length=30), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('block_window_id', sa.Integer(), nullable=False),
    sa.Column('optimization_run_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'MODIFIED', 'REJECTED', 'COMPLETED', name='blockstatus'), nullable=False),
    sa.Column('optimization_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='chk_block_times'),
    sa.ForeignKeyConstraint(['block_window_id'], ['block_windows.id'], ),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['railway_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_opt_block_lookup', 'optimized_blocks', ['section_id', 'status', 'start_time'], unique=False)
    op.create_index(op.f('ix_optimized_blocks_block_code'), 'optimized_blocks', ['block_code'], unique=True)
    op.create_index(op.f('ix_optimized_blocks_block_window_id'), 'optimized_blocks', ['block_window_id'], unique=False)
    op.create_index(op.f('ix_optimized_blocks_optimization_run_id'), 'optimized_blocks', ['optimization_run_id'], unique=False)
    op.create_index(op.f('ix_optimized_blocks_section_id'), 'optimized_blocks', ['section_id'], unique=False)
    op.create_index(op.f('ix_optimized_blocks_status'), 'optimized_blocks', ['status'], unique=False)
    op.create_table('block_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_task_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['optimized_blocks.id'], ),
    sa.ForeignKeyConstraint(['maintenance_task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'maintenance_task_id', name='uq_block_maintenance_task')
    )
    op.create_index(op.f('ix_block_tasks_block_id'), 'block_tasks', ['block_id'], unique=False)
    op.create_index(op.f('ix_block_tasks_maintenance_task_id'), 'block_tasks', ['maintenance_task_id'], unique=False)
    op.create_table('maintenance_compatibility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_a_id', sa.Integer(), nullable=False),
    sa.Column('task_b_id', sa.Integer(), nullable=False),
    sa.Column('compatible', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('task_a_id != task_b_id', name='chk_no_self_compatibility'),
    sa.ForeignKeyConstraint(['task_a_id'], ['maintenance_tasks.id'], ),
    sa.ForeignKeyConstraint(['task_b_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_a_id', 'task_b_id', name='uq_task_pair')
    )
    op.create_index(op.f('ix_maintenance_compatibility_task_a_id'), 'maintenance_compatibility', ['task_a_id'], unique=False)
    op.create_index(op.f('ix_maintenance_compatibility_task_b_id'), 'maintenance_compatibility', ['task_b_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_compatibility_task_b_id'), table_name='maintenance_compatibility')
    op.drop_index(op.f('ix_maintenance_compatibility_task_a_id'), table_name='maintenance_compatibility')
    op.drop_table('maintenance_compatibility')
    op.drop_index(op.f('ix_block_tasks_maintenance_task_id'), table_name='block_tasks')
    op.drop_index(op.f('ix_block_tasks_block_id'), table_name='block_tasks')
    op.drop_table('block_tasks')
    op.drop_index(op.f('ix_optimized_blocks_status'), table_name='optimized_blocks')
    op.drop_index(op.f('ix_optimized_blocks_section_id'), table_name='optimized_blocks')
    op.drop_index(op.f('ix_optimized_blocks_optimization_run_id'), table_name='optimized_blocks')
    op.drop_index(op.f('ix_optimized_blocks_block_window_id'), table_name='optimized_blocks')
    op.drop_index(op.f('ix_optimized_blocks_block_code'), table_name='optimized_blocks')
    op.drop_index('idx_opt_block_lookup', table_name='optimized_blocks')
    op.drop_table('optimized_blocks')
    op.drop_index(op.f('ix_maintenance_tasks_task_code'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_status'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_section_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_priority_score'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_due_date'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_asset_id'), table_name='maintenance_tasks')
    op.drop_index('idx_maint_task_search', table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_train_movements_train_id'), table_name='train_movements')
    op.drop_index(op.f('ix_train_movements_section_id'), table_name='train_movements')
    op.drop_index('idx_train_mov_window', table_name='train_movements')
    op.drop_table('train_movements')
    op.drop_index(op.f('ix_block_windows_window_code'), table_name='block_windows')
    op.drop_index(op.f('ix_block_windows_section_id'), table_name='block_windows')
    op.drop_table('block_windows')
    op.drop_index(op.f('ix_assets_station_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_section_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_railway_sections_start_station_id'), table_name='railway_sections')
    op.drop_index(op.f('ix_railway_sections_section_code'), table_name='railway_sections')
    op.drop_index(op.f('ix_railway_sections_end_station_id'), table_name='railway_sections')
    op.drop_table('railway_sections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trains_train_number'), table_name='trains')
    op.drop_index(op.f('ix_trains_train_code'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_stations_station_code'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_simulation_runs_simulation_code'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_optimization_runs_run_code'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    # ### end Alembic commands ###
