from app.schemas.common import ErrorDetail, ErrorResponse, PaginatedResponse
from app.schemas.domain import (
    StationResponse,
    SectionResponse,
    AssetResponse,
    MaintenanceRequestResponse,
    MaintenanceRequestDetailResponse,
    MaintenanceHistoryResponse,
    TrainResponse,
    TrainScheduleResponse,
    MaintenanceWindowResponse,
    TrafficWindowResponse,
    DashboardResponse,
    OptimizationSummary,
    OptimizationGenerateRequest,
    AIPredictRequest,
    AIPredictResponse,
    SimulationRunRequest,
    BlockTaskResponse,
    OptimizedBlockResponse,
)

__all__ = [
    "ErrorDetail",
    "ErrorResponse",
    "PaginatedResponse",
    "StationResponse",
    "SectionResponse",
    "AssetResponse",
    "MaintenanceRequestResponse",
    "MaintenanceRequestDetailResponse",
    "MaintenanceHistoryResponse",
    "TrainResponse",
    "TrainScheduleResponse",
    "MaintenanceWindowResponse",
    "TrafficWindowResponse",
    "DashboardResponse",
    "OptimizationSummary",
    "OptimizationGenerateRequest",
    "AIPredictRequest",
    "AIPredictResponse",
    "SimulationRunRequest",
    "BlockTaskResponse",
    "OptimizedBlockResponse",
]
