/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as MaintenanceDashboardRouteImport } from './routes/maintenance-dashboard'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as TrainsRouteImport } from './routes/trains'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceDashboardRoute = MaintenanceDashboardRouteImport.update({
  id: '/maintenance-dashboard',
  path: '/maintenance-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainsRoute = TrainsRouteImport.update({
  id: '/trains',
  path: '/trains',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/blocks': typeof BlocksRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/maintenance': typeof MaintenanceRoute
  '/maintenance-dashboard': typeof MaintenanceDashboardRoute
  '/network': typeof NetworkRoute
  '/trains': typeof TrainsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/blocks': typeof BlocksRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/maintenance': typeof MaintenanceRoute
  '/maintenance-dashboard': typeof MaintenanceDashboardRoute
  '/network': typeof NetworkRoute
  '/trains': typeof TrainsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/blocks': typeof BlocksRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/maintenance': typeof MaintenanceRoute
  '/maintenance-dashboard': typeof MaintenanceDashboardRoute
  '/network': typeof NetworkRoute
  '/trains': typeof TrainsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/blocks'
    | '/dashboard'
    | '/insights'
    | '/maintenance'
    | '/maintenance-dashboard'
    | '/network'
    | '/trains'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/blocks'
    | '/dashboard'
    | '/insights'
    | '/maintenance'
    | '/maintenance-dashboard'
    | '/network'
    | '/trains'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/blocks'
    | '/dashboard'
    | '/insights'
    | '/maintenance'
    | '/maintenance-dashboard'
    | '/network'
    | '/trains'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  BlocksRoute: typeof BlocksRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MaintenanceDashboardRoute: typeof MaintenanceDashboardRoute
  NetworkRoute: typeof NetworkRoute
  TrainsRoute: typeof TrainsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance-dashboard': {
      id: '/maintenance-dashboard'
      path: '/maintenance-dashboard'
      fullPath: '/maintenance-dashboard'
      preLoaderRoute: typeof MaintenanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trains': {
      id: '/trains'
      path: '/trains'
      fullPath: '/trains'
      preLoaderRoute: typeof TrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  BlocksRoute: BlocksRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  MaintenanceRoute: MaintenanceRoute,
  MaintenanceDashboardRoute: MaintenanceDashboardRoute,
  NetworkRoute: NetworkRoute,
  TrainsRoute: TrainsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
